fix: correct spacing in command extraction for post_tests.yml

diff --git a/.github/workflows/post_tests.yml b/.github/workflows/post_tests.yml
--- a/.github/workflows/post_tests.yml
+++ b/.github/workflows/post_tests.yml
@@ -140,6 +140,6 @@ jobs:
             for POST_FILE in "${POST_FILES_ARRAY[@]}"; do
               echo "*** ${POST_FILE} | destroy"
               # shellcheck disable=SC1090
-              source <(echo "set -euxo pipefail" ; cat"${POST_FILE}" | mdq '```^bash$'  -o plain) || true
+              source <(echo "set -euxo pipefail" ; cat "${POST_FILE}" | mdq '```^bash$'  -o plain) || true
             done
           fi
