fix: streamline command execution in post_tests.yml
* Updated command execution to remove unnecessary input redirection.
* Improved readability by directly passing variables to `mdq`.
* Ensured consistent error handling and command execution flow.

diff --git a/.github/workflows/post_tests.yml b/.github/workflows/post_tests.yml
--- a/.github/workflows/post_tests.yml
+++ b/.github/workflows/post_tests.yml
@@ -86,25 +86,25 @@ jobs:
             POST_FILES_ARRAY+=("$(find "${PWD}/_posts" -type f -name "*${POST_FILE}*.md")")
           done
 
-          echo "set -euxo pipefail" > "${TMP_DIR}/run.sh"
-
           case "${GH_ACTION}" in
             build)
               MDQ_CODE_BLOCK='```^bash$'
+              echo "set -euxo pipefail" > "${TMP_DIR}/run.sh"
               for (( idx=${#POST_FILES_ARRAY[@]}-1 ; idx>=0 ; idx-- )); do
                 echo "*** ${POST_FILES_ARRAY[idx]} | build"
-                mdq "${MDQ_CODE_BLOCK}" -o plain < "${POST_FILES_ARRAY[idx]}" >> "${TMP_DIR}/run.sh"
+                mdq "${MDQ_CODE_BLOCK}" -o plain "${POST_FILES_ARRAY[idx]}" >> "${TMP_DIR}/run.sh"
               done
               ;;
             destroy)
               MDQ_CODE_BLOCK='```^sh$'
+              echo "set -x" > "${TMP_DIR}/run.sh"
               if aws eks describe-cluster --name "${CLUSTER_NAME}" --query 'cluster.status' &> /dev/null; then
                 export KUBECONFIG="${TMP_DIR}/${CLUSTER_FQDN}/kubeconfig-${CLUSTER_NAME}.conf"
                 aws eks update-kubeconfig --region "${AWS_DEFAULT_REGION}" --name "${CLUSTER_NAME}" --kubeconfig "${KUBECONFIG}" || true
               fi
               for POST_FILE in "${POST_FILES_ARRAY[@]}"; do
                 echo "*** ${POST_FILE} | destroy"
-                mdq "${MDQ_CODE_BLOCK}" -o plain < "${POST_FILE}" >> "${TMP_DIR}/run.sh"
+                mdq "${MDQ_CODE_BLOCK}" -o plain "${POST_FILE}" >> "${TMP_DIR}/run.sh"
               done
               ;;
             *)
@@ -113,7 +113,7 @@ jobs:
               ;;
           esac
 
-          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )eksctl ' && ! command -v eksctl &> /dev/null ; then
+          if mdq "${MDQ_CODE_BLOCK}" "${POST_FILES_ARRAY[@]}" | grep -Eq '(^| )eksctl ' && ! command -v eksctl &> /dev/null ; then
             echo "*** Installing eksctl"
             brew install eksctl
             (
@@ -128,22 +128,22 @@ jobs:
             ) | tee -a "${GITHUB_STEP_SUMMARY}"
           fi
 
-          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )copilot ' && ! command -v copilot &> /dev/null ; then
+          if mdq "${MDQ_CODE_BLOCK}" "${POST_FILES_ARRAY[@]}" | grep -Eq '(^| )copilot ' && ! command -v copilot &> /dev/null ; then
             echo "*** Installing copilot"
             brew install copilot
           fi
 
-          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )cilium ' && ! command -v cilium &> /dev/null ; then
+          if mdq "${MDQ_CODE_BLOCK}" "${POST_FILES_ARRAY[@]}" | grep -Eq '(^| )cilium ' && ! command -v cilium &> /dev/null ; then
             echo "*** Installing cilium"
             brew install cilium-cli
           fi
 
-          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )rain ' && ! command -v rain &> /dev/null ; then
+          if mdq "${MDQ_CODE_BLOCK}" "${POST_FILES_ARRAY[@]}" | grep -Eq '(^| )rain ' && ! command -v rain &> /dev/null ; then
             echo "*** Installing rain"
             brew install rain
           fi
 
-          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )velero ' && ! command -v velero &> /dev/null ; then
+          if mdq "${MDQ_CODE_BLOCK}" "${POST_FILES_ARRAY[@]}" | grep -Eq '(^| )velero ' && ! command -v velero &> /dev/null ; then
             echo "*** Installing velero"
             brew install velero
           fi
