feat: Enhance command extraction in post_tests.yml using mdq (#354)
* feat: enhance post_tests.yml to use mdq for command extraction

* fix: correct spacing in command extraction for post_tests.yml

* fix: streamline command extraction in post_tests.yml by replacing cat with input redirection

* fix: update command extraction in post_tests.yml to specify shell type for improved accuracy

* fix: simplify command extraction in post_tests.yml by removing quotes around array expansion

* fix: update command extraction in post_tests.yml to use quotes for array expansion

* fix: replace input redirection with cat in command extraction for post_tests.yml

* fix: replace input redirection with cat in command checks for post_tests.yml

* fix: refactor command execution in post_tests.yml to use a temporary script for improved readability and maintainability

* fix: correct output redirection in post_tests.yml for command execution

* fix: add error handling for unknown actions in post_tests.yml

diff --git a/.github/workflows/post_tests.yml b/.github/workflows/post_tests.yml
--- a/.github/workflows/post_tests.yml
+++ b/.github/workflows/post_tests.yml
@@ -78,6 +78,7 @@ jobs:
 
           export TMP_DIR="${PWD}"
           eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+          brew install mdq
 
           POST_FILES_ARRAY=()
           # shellcheck disable=SC2043
@@ -85,7 +86,34 @@ jobs:
             POST_FILES_ARRAY+=("$(find "${PWD}/_posts" -type f -name "*${POST_FILE}*.md")")
           done
 
-          if grep -Eq '(^| )eksctl ' "${POST_FILES_ARRAY[@]}" && ! command -v eksctl &> /dev/null ; then
+          echo "set -euxo pipefail" > "${TMP_DIR}/run.sh"
+
+          case "${GH_ACTION}" in
+            build)
+              MDQ_CODE_BLOCK='```^bash$'
+              for (( idx=${#POST_FILES_ARRAY[@]}-1 ; idx>=0 ; idx-- )); do
+                echo "*** ${POST_FILES_ARRAY[idx]} | build"
+                mdq "${MDQ_CODE_BLOCK}" -o plain < "${POST_FILES_ARRAY[idx]}" >> "${TMP_DIR}/run.sh"
+              done
+              ;;
+            destroy)
+              MDQ_CODE_BLOCK='```^sh$'
+              if aws eks describe-cluster --name "${CLUSTER_NAME}" --query 'cluster.status' &> /dev/null; then
+                export KUBECONFIG="${TMP_DIR}/${CLUSTER_FQDN}/kubeconfig-${CLUSTER_NAME}.conf"
+                aws eks update-kubeconfig --region "${AWS_DEFAULT_REGION}" --name "${CLUSTER_NAME}" --kubeconfig "${KUBECONFIG}" || true
+              fi
+              for POST_FILE in "${POST_FILES_ARRAY[@]}"; do
+                echo "*** ${POST_FILE} | destroy"
+                mdq "${MDQ_CODE_BLOCK}" -o plain < "${POST_FILE}" >> "${TMP_DIR}/run.sh"
+              done
+              ;;
+            *)
+              echo "Unknown action: ${GH_ACTION}"
+              exit 1
+              ;;
+          esac
+
+          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )eksctl ' && ! command -v eksctl &> /dev/null ; then
             echo "*** Installing eksctl"
             brew install eksctl
             (
@@ -100,45 +128,25 @@ jobs:
             ) | tee -a "${GITHUB_STEP_SUMMARY}"
           fi
 
-          if grep -Eq '(^| )copilot ' "${POST_FILES_ARRAY[@]}" && ! command -v copilot &> /dev/null ; then
+          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )copilot ' && ! command -v copilot &> /dev/null ; then
             echo "*** Installing copilot"
             brew install copilot
           fi
 
-          if grep -Eq '(^| )cilium ' "${POST_FILES_ARRAY[@]}" && ! command -v cilium &> /dev/null ; then
+          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )cilium ' && ! command -v cilium &> /dev/null ; then
             echo "*** Installing cilium"
             brew install cilium-cli
           fi
 
-          if grep -Eq '(^| )rain ' "${POST_FILES_ARRAY[@]}" && ! command -v rain &> /dev/null ; then
+          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )rain ' && ! command -v rain &> /dev/null ; then
             echo "*** Installing rain"
             brew install rain
           fi
 
-          if grep -Eq '(^| )velero ' "${POST_FILES_ARRAY[@]}" && ! command -v velero &> /dev/null ; then
+          if cat "${POST_FILES_ARRAY[@]}" | mdq "${MDQ_CODE_BLOCK}" | grep -Eq '(^| )velero ' && ! command -v velero &> /dev/null ; then
             echo "*** Installing velero"
             brew install velero
           fi
 
-          if [[ "${GH_ACTION}" =~ 'build' ]]; then
-            echo -e "********************\n*** Create\n********************"
-            for (( idx=${#POST_FILES_ARRAY[@]}-1 ; idx>=0 ; idx-- )); do
-              echo "*** ${POST_FILES_ARRAY[idx]} | build"
-              # shellcheck disable=SC1090
-              source <(echo "set -euxo pipefail" ; sed -n "/^\s*\`\`\`bash$/,/^\s*\`\`\`$/p" "${POST_FILES_ARRAY[idx]}" | sed 's/^\s*```*//')
-            done
-          fi
-
-          if [[ "${GH_ACTION}" =~ 'destroy' ]]; then
-            echo -e "********************\n*** Destroy\n********************"
-            if eksctl get clusters --name="${CLUSTER_NAME}" &> /dev/null; then
-              export KUBECONFIG="${TMP_DIR}/${CLUSTER_FQDN}/kubeconfig-${CLUSTER_NAME}.conf"
-              aws eks update-kubeconfig --region "${AWS_DEFAULT_REGION}" --name "${CLUSTER_NAME}" --kubeconfig "${KUBECONFIG}" || true
-            fi
-
-            for POST_FILE in "${POST_FILES_ARRAY[@]}"; do
-              echo "*** ${POST_FILE} | destroy"
-              # shellcheck disable=SC1090
-              source <(echo "set -euxo pipefail" ; sed -n "/^\`\`\`sh$/,/^\`\`\`$/p" "${POST_FILE}" | sed "/^\`\`\`*/d") || true
-            done
-          fi
+          chmod a+x "${TMP_DIR}/run.sh"
+          "${TMP_DIR}/run.sh"
