ci(post_tests): fix destroy issues caused by eksctl

diff --git a/.github/workflows/post_tests.yml b/.github/workflows/post_tests.yml
--- a/.github/workflows/post_tests.yml
+++ b/.github/workflows/post_tests.yml
@@ -29,6 +29,8 @@ on:
 env:
   AWS_DEFAULT_REGION: us-east-1
   AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+  # renovate: datasource=github-tags depName=weaveworks/eksctl
+  EKSCTL_VERSION: 0.146.0
   GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
   GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
 
@@ -71,7 +73,7 @@ jobs:
 
           if grep -q eksctl "${POST_FILES_ARRAY[@]}" && ! command -v eksctl &> /dev/null ; then
             echo "*** Installing eksctl"
-            gh release download --repo weaveworks/eksctl --pattern eksctl_Linux_amd64.tar.gz --output - | sudo tar xz -C /usr/local/bin/
+            gh release download --repo weaveworks/eksctl --pattern eksctl_Linux_amd64.tar.gz "v${EKSCTL_VERSION}" --output - | sudo tar xz -C /usr/local/bin/
           fi
 
           if grep -q velero "${POST_FILES_ARRAY[@]}" && ! command -v velero &> /dev/null ; then
@@ -111,6 +113,6 @@ jobs:
             for POST_FILE in "${POST_FILES_ARRAY[@]}"; do
               echo "*** ${POST_FILE} | destroy"
               # shellcheck disable=SC1090
-              source <(echo "set -ux" ; sed -n "/^\`\`\`sh$/,/^\`\`\`$/p" "${POST_FILE}" | sed "/^\`\`\`*/d") || true
+              source <(echo "set -euxo pipefail" ; sed -n "/^\`\`\`sh$/,/^\`\`\`$/p" "${POST_FILE}" | sed "/^\`\`\`*/d") || true
             done
           fi
