docs(posts): add 2022-12-24-amazon-eks-karpenter-tests (#39)

diff --git a/.github/workflows/post_tests.yml b/.github/workflows/post_tests.yml
--- a/.github/workflows/post_tests.yml
+++ b/.github/workflows/post_tests.yml
@@ -11,6 +11,7 @@ on:
         required: true
         options:
           - 2022-11-27-cheapest-amazon-eks
+          - 2022-12-24-amazon-eks-karpenter-tests 2022-11-27-cheapest-amazon-eks
       action:
         type: choice
         description: Select action
@@ -26,6 +27,9 @@ env:
   AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
   # renovate: datasource=github-tags depName=weaveworks/eksctl
   EKSCTL_VERSION: 0.124.0
+  # renovate: datasource=github-tags depName=kubernetes-sigs/krew
+  KREW_VERSION: 0.4.3
+  KREW_PLUGINS: cost resource-capacity
   GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
   GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
 
@@ -50,16 +54,24 @@ jobs:
       - name: Check out repository code
         uses: actions/checkout@v3
 
-      - name: Install eksctl
+      - name: Install eksctl, krew and eks-node-viewer
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
           set -euxo pipefail
           gh release download --repo weaveworks/eksctl --pattern eksctl_Linux_amd64.tar.gz "v${EKSCTL_VERSION}" --output - | sudo tar xz -C /usr/local/bin/
+          gh release download --repo kubernetes-sigs/krew --pattern krew-linux_amd64.tar.gz "v${KREW_VERSION}" --output - | sudo tar xz -C /tmp/
+          /tmp/krew-linux_amd64 install krew
+          echo "${HOME}/.krew/bin" >> "${GITHUB_PATH}"
+
+      - name: Install krew plugins
+        run: |
+          set -euxo pipefail
+          kubectl krew install ${{ env.KREW_PLUGINS }}
 
       - name: "${{ inputs.action }} | ${{ inputs.posts }}"
         run: |
-          set -euo pipefail
+          set -euxo pipefail
 
           POST_FILES_ARRAY=()
           # shellcheck disable=SC2043
@@ -68,11 +80,11 @@ jobs:
           done
 
           if [[ "${{ inputs.action }}" =~ 'build' ]]; then
-            for POST_FILE in "${POST_FILES_ARRAY[@]}"; do
-              echo "*** ${POST_FILE} | build"
+            for (( idx=${#POST_FILES_ARRAY[@]}-1 ; idx>=0 ; idx-- )); do
+              echo "*** ${POST_FILES_ARRAY[idx]} | build"
               # shellcheck disable=SC1090
-              source <(echo "set -euxo pipefail" ; sed -n "/^\`\`\`bash$/,/^\`\`\`$/p" "${POST_FILE}" | sed "/^\`\`\`*/d")
-              if [[ "${POST_FILE}" =~ eks ]]; then
+              source <(echo "set -euxo pipefail" ; sed -n "/^\`\`\`bash$/,/^\`\`\`$/p" "${POST_FILES_ARRAY[idx]}" | sed "/^\`\`\`*/d")
+              if [[ "${POST_FILES_ARRAY[*]}" =~ eks && ${idx} -eq ${#POST_FILES_ARRAY[@]}-1 ]]; then
                 (
                   echo '```'
                   # shellcheck disable=SC2028
@@ -86,8 +98,8 @@ jobs:
           fi
 
           if [[ "${{ inputs.action }}" =~ 'destroy' ]]; then
-            for (( idx=${#POST_FILES_ARRAY[@]}-1 ; idx>=0 ; idx-- )); do
-              echo "*** ${POST_FILES_ARRAY[idx]} | destroy"
-              sed -n "/^\`\`\`sh$/,/^\`\`\`$/p" "${POST_FILES_ARRAY[idx]}" | sed "/^\`\`\`*/d" | bash -euxo pipefail
+            for POST_FILE in "${POST_FILES_ARRAY[@]}"; do
+              echo "*** ${POST_FILE} | destroy"
+              sed -n "/^\`\`\`sh$/,/^\`\`\`$/p" "${POST_FILE}" | sed "/^\`\`\`*/d" | bash -euxo pipefail
             done
           fi
