feat(tests): improve tests by adding AWS role and EKS access description

diff --git a/.github/workflows/post_tests.yml b/.github/workflows/post_tests.yml
--- a/.github/workflows/post_tests.yml
+++ b/.github/workflows/post_tests.yml
@@ -23,6 +23,7 @@ on:
 
 env:
   AWS_DEFAULT_REGION: us-east-1
+  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
   # renovate: datasource=github-tags depName=weaveworks/eksctl
   EKSCTL_VERSION: 0.123.0
 
@@ -67,7 +68,19 @@ jobs:
           if [[ "${{ inputs.action }}" =~ 'build' ]]; then
             for POST_FILE in "${POST_FILES_ARRAY[@]}"; do
               echo "*** ${POST_FILE} | build"
-              sed -n "/^\`\`\`bash$/,/^\`\`\`$/p" "${POST_FILE}" | sed "/^\`\`\`*/d" | bash -euxo pipefail
+              # shellcheck disable=SC1090
+              source <(echo "set -euxo pipefail" ; sed -n "/^\`\`\`bash$/,/^\`\`\`$/p" "${POST_FILE}" | sed "/^\`\`\`*/d")
+              if [[ "${POST_FILE}" =~ eks ]]; then
+                (
+                  echo '* :low_brightness:'
+                  echo '  ```'
+                  # shellcheck disable=SC2028
+                  echo "  eval \"\$(aws sts assume-role --role-arn \"\${AWS_ROLE_TO_ASSUME}\" --role-session-name \"\$USER@\$(hostname -f)-k8s-\$(date +%s)\" --duration-seconds 36000 | jq -r '.Credentials | \"export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\\nexport AWS_SESSION_TOKEN=\(.SessionToken)\\n\"')\""
+                  echo "  export KUBECONFIG=\"/tmp/kubeconfig-${CLUSTER_NAME}.conf\""
+                  echo "  aws eks update-kubeconfig --region \"${AWS_DEFAULT_REGION}\" --name \"${CLUSTER_NAME}\" --kubeconfig \"\$KUBECONFIG\""
+                  echo '  ```'
+                ) | tee -a "${GITHUB_STEP_SUMMARY}"
+              fi
             done
           fi
 
